// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTKVLWMkZ4gFTdyi9bqUZYW5Jh9aJ6k-0',
    appId: '1:51580470988:web:6db184286c70cd2da5a469',
    messagingSenderId: '51580470988',
    projectId: 'activesol',
    authDomain: 'activesol.firebaseapp.com',
    storageBucket: 'activesol.firebasestorage.app',
    measurementId: 'G-WVXH19D3KE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUyTYj-QCz1Ekzz0IfK8CCi7tdtJMp5h4',
    appId: '1:51580470988:android:822a4351d538ece8a5a469',
    messagingSenderId: '51580470988',
    projectId: 'activesol',
    storageBucket: 'activesol.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDVCG9IaguIw6P3K2c4XKLI1AwM_KIVQQ',
    appId: '1:51580470988:ios:cfca5bf800f9fb5da5a469',
    messagingSenderId: '51580470988',
    projectId: 'activesol',
    storageBucket: 'activesol.firebasestorage.app',
    iosBundleId: 'com.example.activeSolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDVCG9IaguIw6P3K2c4XKLI1AwM_KIVQQ',
    appId: '1:51580470988:ios:cfca5bf800f9fb5da5a469',
    messagingSenderId: '51580470988',
    projectId: 'activesol',
    storageBucket: 'activesol.firebasestorage.app',
    iosBundleId: 'com.example.activeSolApp',
  );
}
